### ISSUE TITLE
Upgrade To Latest Wike Versions (v2.0.0 +)

### ISSUE THREAD

**Issue by CapeCrusader321** [CapeCrusader321/Wike-Snap#3]
This wont be possible until next year as the current snap core22 and gnome-sdk lacks webkit6 needed by newer wike versions and as such newer versions will be available once Core24 arrives, stay tuned

**Comment by soumyaDghosh** [comment]
Don't worry, expect this upgrade within July :wink:

**Comment by CapeCrusader321** [comment]
> Don't worry, expect this upgrade within July wink
> 
> EDIT: Want to update now??

Sorry for late reply, Are there plans to merge webkit6 in gnome-sdk by July ??

**Comment by CapeCrusader321** [comment]
> I would like to know a direct answer first.
> 
> Want to update now? slightly_smiling_face

Maybe/Maybe not, if possible i have no problem, as my end goal is to provide newer versions ??

**Comment by soumyaDghosh** [comment]
I will share you a PR tomorrow then.!!!!
